#!/usr/bin/env php
<?php

/*
| Francesca Framework
| https://francesca.io
|
| Copyright 2017, Andrea Pollastri
| Released under the MIT license
|
|
|
|------------------------------------------------------------------------
| CLI manager - cli.php
|------------------------------------------------------------------------
| This page lets you use php CLI Francesca Framework "special commands".
|
*/


//CLI CHECK
if(PHP_SAPI == 'cli') {

	//FRANCESCA.IO FRAMEWORK CLI SCRIPTS INCLUDE
	require(__DIR__ ."/libs/functions/cli.php");

} else {

	//FRANCESCA.IO FRAMEWORK CLI PAGE HTTP MESSAGGE
	require_once($_SERVER['DOCUMENT_ROOT']."/libs/functions/template.php");
	fra_template("<b>ERROR!</b> CLI tools are not enable by HTTP requests!");

}

